### ISSUE TITLE
google message dialogs show up all the time if I access the private sheet

### ISSUE THREAD

**Issue by bestwnh** [chriszarate/sheetrock#100]
Great library, save my day. 
But when I try to access a private sheet(I own the file and already signed in), it can get the data but also show up a dialogs with the text below all the time.
`Access to Google Sheets data from this web page will soon start failing.  For information on fixing this, see https://g.co/sheets/3p-auth-changes.`
![screen shot 2016-09-13 at 16 19 18](https://cloud.githubusercontent.com/assets/1201345/18466593/e63c2f6e-79ce-11e6-98ad-2175b1a13e04.png)

Is there any way to prevent this? And would the library fail just like it mention?

**Comment by chriszarate** [comment]
Sheetrock is intended to work with public Google Sheets. The fact that it _can_ work with private Sheets when signed in to Google in the same browser has always been an unsupported quirk (and it says so in the README).

Unfortunately, it appears Google will soon close the loophole that permitted this quirk. There is no workaround. I'll update the README accordingly.

Sheetrock will continue to work as expected with public Sheets.

**Comment by bestwnh** [comment]
Can't it solve by send an access token or something? If there is any way to do that but you not ready to support that, you can provide me the related url and I may implement it myself. But I just not very clear about this with the google document.

**Comment by chriszarate** [comment]
It's not impossible, just impractical for a client-side library. In effect, yes, sending an access token could work, but obtaining that access token means implementing an OAuth2 flow—or walking through it manually and saving that token for reuse.

https://developers.google.com/chart/interactive/docs/spreadsheets#authorization
