### ISSUE TITLE
1.1.0 - Breaking Changes?

### ISSUE THREAD

**Issue by tjferry14** [chriszarate/sheetrock#101]
Does ES2015 contain any major changes? The reason I ask is because things that worked perfect before now return an error after upgrading to 1.1.0.

Update: I thought it was a problem with Handlebars 4.0, but even at 3.0.2 this happens.

**Comment by chriszarate** [comment]
If you can throw up an example that illustrates the issue I can take a look. There shouldn't be any breaking changes (other than the removal of the environment property as documented by the CHANGELOG), but I couldn't rule out an error on my part.

**Comment by tjferry14** [comment]
https://github.com/mummers/sb-media You can see the repo I'm working with here

**Comment by chriszarate** [comment]
Ok, might not be able to take a look tonight but will do so soon.

**Comment by tjferry14** [comment]
I appreciate it very much. We are using sheetrock for another project you can check out here if you'd like: https://mummers.github.io/stringbands/

**Comment by chriszarate** [comment]
Thanks for the report! Fixed in `1.1.1`.
