### ISSUE TITLE
Trying to refresh the data so it's live - Uncaught Error: No more rows to load!

### ISSUE THREAD

**Issue by DrewGamble** [chriszarate/sheetrock#103]
Hi there!

I'm trying to use sheetrock to display a cell value from a googlesheet that i'm constantly updating to display the value live. I've managed to get the value to display, but with an interval of 5 seconds, it doesn't update, instead it gives me the error of Uncaught Error: No more rows to load! then after looking further into the console it's because "// Abandon requests that have already been loaded." Is there a way I can have the value be constantly updated with the value of the cell? (listed below code)

`<div class="stat">`
            `<p>$<span class="total"></span> raised so far!</p>`
`</div>`

`<script>`
`setInterval(function(){`
            `var mySpreadsheet = 'https://docs.google.com/spreadsheets/d/1ikee8mXd3TcnFTml2A5O4KAldL0Fg-xlnGp8ucBqAtY/pubhtml?gid=0&single=true'`
        
            $('.total').sheetrock({
                url: mySpreadsheet
            })
        
       }, 2000);
`</script>`

**Comment by chriszarate** [comment]
Use the `reset` option, e.g.:

```js
var mySpreadsheet = 'https://docs.google.com/spreadsheets/d/1ikee8mXd3TcnFTml2A5O4KAldL0Fg-xlnGp8ucBqAtY/pubhtml?gid=0&single=true';

setInterval(function() {
  $('.total').sheetrock({
    url: mySpreadsheet,
    reset: true
  });
}, 2000);
```

**Comment by DrewGamble** [comment]
I've tried that but when using the reset option, the data doesn't load at all (see image). Without the reset option, the function retrieves the information, but only once until the page is refreshed

![](https://i.gyazo.com/fcd74434c3ef25a8cc263cbaaa510a45.png)

**Comment by chriszarate** [comment]
Two problems here:

1. Your spreadsheet has only one row and it's being treated as a header row. Try moving your data down to A2 and putting a header label like "Total" in A1. Alternatively, "unfreeze" the row via the View menu.

2. If you don't pass a template, Sheetrock doesn't know how to represent the data. It will try to represent it as a table, but you're targeting a `<span>` tag, which probably isn't what you want. Either target a `table` element (e.g., `<table class="total">` or pass a template, e.g.:

```js
// Make sure Handlebars is available.
var template = Handlebars.compile('{{cells.Total}}');

var mySpreadsheet = 'https://docs.google.com/spreadsheets/d/1ikee8mXd3TcnFTml2A5O4KAldL0Fg-xlnGp8ucBqAtY/pubhtml?gid=0&single=true';

setInterval(function() {
  $('.total').empty().sheetrock({
    url: mySpreadsheet,
    rowTemplate: template,
    reset: true
  });
}, 2000);
```

Note that you'll might also want to append `.empty()` to the jQuery object before you call Sheetrock to make sure that the response from the previous request is removed.

**Comment by DrewGamble** [comment]
Aha! That did the trick. The function works perfectly now. Thank you for helping!
