### ISSUE TITLE
Error: Unexpected API response format after using reset: true

### ISSUE THREAD

**Issue by papoms** [chriszarate/sheetrock#104]
Hey,

i am trying to use the reset(:true) option in a project to reset the row offset (after changing the query e.g. to apply a new filter and start over with the first row). 
While this works for the first request, all consecutive requests (with reset: false to load more data) fail with "Error: Unexpected API response format.". 

Here is a simple jsFiddle based on your Demo (request output on the console):
https://jsfiddle.net/papoms/saygfvm7/28/

1) Click on Button with reset: true works just fine.
2) Uncheck Reset and Click Button again to send a second request with reset: false

=> "Error: Unexpected API response format" (on console)

Maybe you can shed some light on this or push me into the right direction

**Comment by chriszarate** [comment]
This looks like a bug. It seems restricted to setting `reset` to `true` and then later setting it to `false`. (The other way around seems fine.) I'll need to take a closer look, probably later this week.
