### ISSUE TITLE
Save query result in variable

### ISSUE THREAD

**Issue by felixbrabant** [chriszarate/sheetrock#107]
Hi,

I'm looking fo a way to save the result of a query in a variable, instead of putting into a div. I'd like to do that because I'm using the data in other parts of another script.

Thanks!

Felix

P.S.: Newbie in JS/jQuery, so please excuse me if my question doesn't make any sense :)

**Comment by tjferry14** [comment]
+1 for this, or even a suggestion on how to pull a random row.

**Comment by halloway** [comment]
+1
It would really be great to store the result in a variable instead of putting it into HTML straight away.

**Comment by chriszarate** [comment]
Use the `callback` option to access the returned data. Then you can do whatever you want with it:

```js
sheetrock({
  url: '...',
  callback: myCallback
});

function myCallback(error, options, response) {
  if (error) {
    return;
  }

  // Log response.data to the console so that you can explore its format
  // and decide how you want to use it.
  console.log(response.data);
}
```
