### ISSUE TITLE
unable to view the image

### ISSUE THREAD

**Issue by selvamurali** [chriszarate/sheetrock#108]
Dear team i am unable to view the image when i insert in a Cell
kindly advise how can i show the image in html from google sheet
tks

**Comment by tjferry14** [comment]
I think you'll have to be a little more specific on your issue. Are you loading the image through a link or directly in the cell? I don't think Sheetrock supports images.

**Comment by chriszarate** [comment]
Sheetrock doesn't natively support images, but if you know the data is an image URL, you could use the `callback` option and manually create an image and append it to the page.

**Comment by leolamanna** [comment]
> 
Hi! Is there any resource to help on that?? Any sample reference? Thanks in advance!

**Comment by leolamanna** [comment]
> Sheetrock doesn't natively support images, but if you know the data is an image URL, you could use the `callback` option and manually create an image and append it to the page.

Hi! Is there any resource to help on that?? Any sample reference? Thanks in advance!
