### ISSUE TITLE
Sheetrock should provide a better error message when user's template throws an error

### ISSUE THREAD

**Issue by tjferry14** [chriszarate/sheetrock#111]
Thanks for all your help recently. I'm using the code below to load up my table in handlebars. It's just like everything I normally write, yet I still am getting an API error. See [this JS Fiddle](https://jsfiddle.net/v0ypkLp4/54/) for what I am trying to accomplish. 

```
function loadResults(sql, table) {
  $(table).sheetrock({
    url: mySpreadsheet,
    query: sql,
    rowTemplate: bandsTemplate,
    callback: myCallback
  });
}

function myCallback(error, options, response) {
  if (!error) {
    if ($('#bands tr').length == 1) {
      $('#bands').append("<h3>No results.</h3>")
    }
  } else {
    $('#bands').append('<h3>' + error + '</h3>');
  }
};

```

**Comment by chriszarate** [comment]
Your Handlebars template is not valid. In two places you are using the token `normalize` which causes a parsing error when the template runs.

Sheetrock should probably provide a better error message when this happens. I'm going to rename the issue and leave this open.

**Comment by tjferry14** [comment]
Didn't realize that was the issue. Thought I was doing everything ok. Thanks for clearing it up.
