### ISSUE TITLE
Overriding default callback function

### ISSUE THREAD

**Issue by tjferry14** [chriszarate/sheetrock#113]
Would the proper way to over ride/set the new callback function be `sheetrock.defaults.callback = myCallback;`? I tried multiple things that don't seem to work.  `sheetrock.defaults.callback = myCallback(error, options, response);` gives an error because of the variables needing to be there. Can you even set a callback function separately?

**Comment by chriszarate** [comment]
The most straightforward way to provide a callback function is to pass it by reference each time you call Sheetrock, e.g.:

```js
function myCallback (error, options, response) {
  /* your code */
}

sheetrock({
  url: '...',
  callback: myCallback
});
```

You could also override Sheetrock's defaults and provide a default callback function—or, at least, you could if a bug wasn't preventing it from working. I'll push a fix in a minute.

```js
function myCallback (error, options, response) {
  /* your code */
}

sheetrock.defaults.callback = myCallback;

sheetrock({
  url: '...'
});
```

**Comment by tjferry14** [comment]
I thought I was doing it correctly. Thanks for investigating for me!

**Comment by tjferry14** [comment]
Any reason why this still wouldn't be working?

**Comment by chriszarate** [comment]
Are you loading the new version (1.1.4)?

**Comment by tjferry14** [comment]
Yep, as soon as you released it last night I updated my code.

**Comment by tjferry14** [comment]
See my fiddle for a direct look at what I'm trying to accomplish: https://jsfiddle.net/3Lv65jog/2/
