### ISSUE TITLE
filters in sheet affect returned data

### ISSUE THREAD

**Issue by ooobo** [chriszarate/sheetrock#114]
I was missing a few rows of data when using sheetrock, and realised that they were hidden in the spreadsheet by way of a <strong>filter > filter by value</strong>. This may just be a quirk of the underlying visualization api, but is there a way to ignore the filter?
Turning off the filter in the spreadsheet returned all the rows as expected.
Cheers, thanks for such a great resource!

**Comment by chriszarate** [comment]
No, there's no way to turn off the filter via Sheetrock. Filtering is similar to sorting and other functions that effectively edit your view of spreadsheet. It makes sense for the API to reflect that.

**Comment by ooobo** [comment]
Ah, makes sense, thanks.
