### ISSUE TITLE
Uncaught Error: Unexpected API response format.

### ISSUE THREAD

**Issue by jwoyak** [chriszarate/sheetrock#121]
Trying to do what seems like a simple query and getting a very cryptic error in Chrome's js console:

Uncaught Error: Unexpected API response format.
    at new t (error.js:2)
    at e.value (response.js:133)
    at n (transport-browser.js:20)
    at tq?gid=0&tq=select D%2CE where E %3D 2 limit 6 offset 0&tqx=responseHandler:_sheetrock_callback_0:2

I am calling sheetrock from an init() function (since i don't want it to load till the user makes a choice in a dropdown).  Here's entire js file:

var publicSpreadsheetUrl = 'https://docs.google.com/spreadsheets/d/1Owv5v8WZoHpOCi1dxEJBxPO71FZQbqKhe-QyL2FfF7E/edit#gid=0';

function init() {
  var teacherQuery = "select D,E where E = " + window.selectedGrade;
  console.log(teacherQuery)
  $('#teachers').sheetrock({
    url: publicSpreadsheetUrl,
    query: teacherQuery,
    fetchSize: 5,
    rowTemplate: TeacherTemplate
  });

}
  
// Compile the Handlebars template for teachers
var TeacherTemplate = Handlebars.compile($('#teacher-template').html());

function getGrade(selectObject) {
  window.selectedGrade = selectObject.value;
  document.getElementById("chosenGrade").innerHTML = window.selectedGrade;
  init();
  //window.addEventListener('DOMContentLoaded', init);
}

Here's the HTML code too for the sake of completeness:

`<html>
  <head>
    <title>srt: sheetrock test</title>    
  </head>
  <body>
    <div id="col1">
      <div class="outerdiv" id="title1div">
          <h1>sheetrock Test</h1>
      </div>
      <div class="outerdiv" id="insctdiv">
          <p>This is a test of sheetrock and using gSheets via JS.</p>
      </div>
      <div class="outerdiv" id="iptdiv">
        <strong>Step 1: Select Your Grade</strong><br />
        <select name="grade" onchange="getGrade(this)">
          <option value="k" selected="selected">Kindergarten</option>
          <option value="1">Grade 1</option>
          <option value="2">Grade 2</option>
          <option value="3">Grade 3</option>
          <option value="4">Grade 4</option>
          <option value="5">Grade 5</option>
        </select>
      </div>
      <div class="outerdiv" id="gradediv">
          You chose grade:<br />
          <p id="chosenGrade"></p>
      </div>
    </div>
    <div class="outerdiv" id="col2">
        <p id="listText"></p>
    </div>
    <div class="outerdiv" id="col2">
        <h3>Teachers:</h3>
        <select id="teachers">
          <script id="teacher-template" type="text/x-handlebars-template">
            <option id="results" value="{{cells.First}}">
              {{cells.First}}
            </option>
          </script>
        </select>
    </div>

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-sheetrock/1.1.4/dist/sheetrock.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.5/handlebars.min.js"></script>   
    <script src="sheetrockTest.js"></script>
  </body>
</html>`

Sorry for my sloppy code as i'm sadly new to js.   Any insight into this would be very appreciated!

thanks for all your work making sheetrock!

Jason

**Comment by jwoyak** [comment]
Just a quick update on this, i caught a few stupid errors in my code (I didn't have the correct field names in the html.  It is still doing the same exact thing, however.  I also added a callback to get more diagnostic info. If you'd like the output of that i can add it here.

thanks!

**Comment by chriszarate** [comment]
Here's a working (simplified) version of your code:

https://jsfiddle.net/qemm964x/

I'm guessing the issue you ran into is not passing a string to your query. For example, if you simply pass `K` as the grade to query, Google will interpret it as a column reference. Instead, you need to wrap it in quotes so that Google interprets it as a string: `"K"`.

It's also helpful to inspect in the error console so that you can see the details of the error. To help with this, I often pass the following callback parameter to my Sheetrock request, which logs everything to the console:

`callback: function(error, options, response) { console.log(error, options, response): }`

**Comment by jwoyak** [comment]
Wow thank you for taking the time to look at this and for posting the jsfiddle.  That helped me a lot, and my app is working now.  Thanks for making such a useful library, and for taking the time to support it.

Jason
