### ISSUE TITLE
Order of Query Importance

### ISSUE THREAD

**Issue by tjferry14** [chriszarate/sheetrock#122]
How important is the order of the query? Using "select O,count(C),A group by O order by O" gives me an error, so I was wondering if the order had anything to do with it

**Comment by chriszarate** [comment]
The docs are pretty clear about the necessary order:

https://developers.google.com/chart/interactive/docs/querylanguage#language-clauses

I think your error is probably related to your use of `group by`:

"Note: If you use a group by clause, then every column listed in the select clause must either be listed in the group by clause, or be wrapped by an aggregation function."
