### ISSUE TITLE
Usage question and updating data on the fly

### ISSUE THREAD

**Issue by zachwhalen** [chriszarate/sheetrock#14]
Hi,

First of all, sheetrock is amazing. I'm loving it. I just have run into something I can't figure out how to do, and since I didn't see it in the documentation, I thought I'd ask here. Hopefully that's OK.  It's probably something fundamental that I'm misunderstanding, but maybe not.

What I'm trying to do is have some data in a sheetrock object in my DOM that changes based on other things that go on. Like, hit a button to select a player's name, and then "#playerdata" (in my case) gets updated with new contents based on a new query that selects for that player's name.

Works fine the first time through, but the second time triggers the "No more rows to load!" console message.

Is it possible to unload the first query and reattach it to the same #playerdata? Or should I be thinking of this differently altogether? 

I thought about chunking, but if I'm not mistaken that would depend on knowing the row order, which wouldn't help if I'm trying to pull out unique record.

Thanks,
Zach

**Comment by DiogoSouza** [comment]
I had this problem too. Just for other people to know, now we have the option attribute "resetStatus": https://github.com/chriszarate/sheetrock#resetstatus.

I just set it to true and it worked. Thanks, great plugin.. Congrats! :+1:
