### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by vintaclectic** [chriszarate/sheetrock#146]
Hey there, 3 days ago my simple application i made using your sheetrock.js stopped working. I notice you also seemed to do some updates 3 days ago... I have been using this same setup for over a year now, I believe, and never once had a single issue. Ran like a champ. What if at all possible would you think changed in last 3 days that made it stop working entirely? There's zero errors, it seems to be fetching the query but literally nothing is stating why the results are no longer showing up. Was there a .js change to anything in particular or otherwise? Any help would be awesome! 

Thanks so much!

**Comment by chriszarate** [comment]
You can read about the changes in the CHANGELOG, but it sounds like I introduced a bug. Can you provide some more detail?Any errors in the console?

You can use the previous version by pointing here:
https://unpkg.com/sheetrock@1.1.4/dist/sheetrock.min.js

**Comment by vintaclectic** [comment]
Absolutely zero errors in the console, but will try and see if it works again with old version real quick and get back to you. thanks!

**Comment by vintaclectic** [comment]
Works again with the old version! Thanks so much.
