### ISSUE TITLE
Uncaught TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by rafaelcastrocouto** [chriszarate/sheetrock#147]
This error is happening on the jsbin example at readme.md (and everywhere else)

util.js:24
    at options.js:25
    at new c (options.js:69)
    at n.fn.init.b [as sheetrock] (index.js:44)

https://jsfiddle.net/chriszarate/p1kxjwgq/

**Comment by chriszarate** [comment]
Thanks for letting me know, @rafaelcastrocouto. The examples use jQuery. JSFiddle used to load jQuery by default, but now doesn't. I updated the examples I link to so that they load jQuery explicitly. Let me know if you find any that still aren't working.
