### ISSUE TITLE
Google API sometimes asks for login credentials

### ISSUE THREAD

**Issue by matthewjonesaus** [chriszarate/sheetrock#28]
SheetRock appears to have stopped working on iOS devices - viewing a SheetRock-powered table on an iPad or iPhone now shows a blank space (see screenshot).
![photo](https://f.cloud.github.com/assets/4384846/2131995/5c90794c-92a8-11e3-8185-61ead645f3cd.png)

**Comment by chriszarate** [comment]
Closing as I haven't seen this issue come up in awhile. One thing that seems to help prevent this issue is to remove any Google Apps identifiers (e.g., `/a/myorg.com`) from the URL, just after the first slash.
