### ISSUE TITLE
Update data without refreshing the page?

### ISSUE THREAD

**Issue by thekingsrook** [chriszarate/sheetrock#29]
Thanks for Sheetrock! I'm not sure if this is obvious or an irrelevant question (I'm new to web dev), but how would I go about getting the data asynchronously?

When I edit and save my Google Spreadsheet, I have to refresh my browser to see the changes in the table. Is there a way to get the changes displayed in the table automatically, without refreshing the page? Sorry if this is asking too much or doesn't apply to Sheetrock.

**Comment by rengelmann** [comment]
Try adding resetStatus: true to the code. This forces a reload. However, it seems to append the table over and over, so you also have to clear it first somehow.
like so

    setInterval(function() {
        $('#statistics').html('').sheetrock({
          resetStatus: true,
          url: mySpreadsheet,
        });  
    }, 2000);

**Comment by buya2002mgl** [comment]
Guys, I'm looking for implementation of SheetRock with pagination, sorting and filtering etc.
