### ISSUE TITLE
How to set new Google Spreadsheet Row 1 as default Table Head Data

### ISSUE THREAD

**Issue by coldes** [chriszarate/sheetrock#39]
Hello - first of all this is a "schoolboy error" query. 

I can not work out how to set in a new google spreadsheet the first row to be the table header. All I get is A, B, C, etc in web page

This is my code to not show  A, B, C, in web table header row :

$('#programme').sheetrock({
  url: mySpreadsheet,
  sql: "select A,B,C",
  headersOff: true
});

What I can not work out is how the sample baseball spreadsheet achieved the first row displaying as the Table Header

The documentation on Columns and Labels just confuses me

Assistance would be greatly appreciated
 thanks, Col

PS: Want to keep this GS-to-Table simple and not use any Templating

**Comment by fraguada** [comment]
I am getting a similar issue.  I have a column C where "Diffuse" is the first Cell (C1).  I'd like to also select based on the header name instead of C like so (select C works):

sql: "select %Diffuse%"

But I get this error: 

Invalid query: PARSE_ERROR Encountered "%" at line 1, column 8.
Was expecting one of:
    "true" ...
    "false" ...
    "date" ...
    "timeofday" ...
    "datetime" ...
    "timestamp" ...
    "min" ...
    "max" ...
    "avg" ...
    "count" ...
    "sum" ...
    "no_values" ...
    "no_format" ...
    "is" ...
    "null" ...
    "year" ...
    "month" ...
    "day" ...
    "hour" ...
    "minute" ...
    "second" ...
    "millisecond" ...
    "with" ...
    "contains" ...
    "starts" ...
    "ends" ...
    "matches" ...
    "like" ...
    "now" ...
    "dateDiff" ...
    "quarter" ...
    "lower" ...
    "upper" ...
    "dayOfWeek" ...
    "toDate" ...
    <ID> ...
    <INTEGER_LITERAL> ...
    <DECIMAL_LITERAL> ...
    <STRING_LITERAL> ...
    <QUOTED_ID> ...
    "(" ...
    "*" ...
    "-" ...
    

jquery.....min.js (line 7)

**Comment by chriszarate** [comment]
I've just published a new version (`1.0.0`) of Sheetrock. The options have changed (make sure to review README), but the approach is much simpler with respect to header rows. It expects a single header row in row 1, but should work more or less without configuration.
