### ISSUE TITLE
Guidance on how to access a private Google spreadsheet

### ISSUE THREAD

**Issue by dperkel** [chriszarate/sheetrock#41]
Thanks for sharing this really powerful tool. It's almost exactly what I'm looking for. I'd like to be able to use Sheetrock to access a private Google Spreadhseet rather than a public one. 

Any guidance on how to go about doing this, or whether this is already something on your radar, would be much appreciated. Thanks in advance.

**Comment by paulreimer** [comment]
I tried this today, and... it didn't seem to work. Using a test sheet worked fine when public, and stopped working when private. I am logged in to my GSuite account -- the link works otherwise.

Maybe Google Sheets API is different enough now, that this is no longer supported?

**Comment by paulreimer** [comment]
FYI the JS console error was:
```
Error: Unexpected API response format.
    at new t (error.js:2)
    at e.value (response.js:133)
    at n (transport-browser.js:20)
    at tq?gid=0&tq=&tqx=responseHandler:_sheetrock_callback_0:2 e e
```
