### ISSUE TITLE
Hyperlinks in Google Spreadsheet to also show as active links in webpage table

### ISSUE THREAD

**Issue by coldes** [chriszarate/sheetrock#42]
Hello Chris - Hyperlinks in Google Spreadsheet to also show as active links in webpage table - is this possible? - thanks, Col

**Comment by chriszarate** [comment]
Closing, feel free to reopen with additional info.

**Comment by coldes** [comment]
I have come up with a way of adding a link to a table cell once a google spreadsheet is loaded. Am using setTimeout to append some html. This works fine, however rather than relying on setTime out, I can't figure out a way to only have the html appended ONCE the google spreadsheet 'table' has indeed been loaded. I feel the setTime out can be a bit hit-n-miss due to any delay and the timeout has passed before spreadsheet has fully loaded.

Not sure if this can be part of a callback function? 

Anyway, my scenario. Am loading multiple spreadsheets 'tables' into a modal window using .on click function. The first  loaded Table, 2nd row, 2nd cell is where I append a link [in this case to allow a scroll down to another table below viewport. Even though I could add this as static markup to my existing modal html before loading spreadsheets, due to the information in this table sell, it is a nice touch to see the link in the loaded cell. Also this append method could have further viability re the original issue topic.

The append method is achieved by [mock example code]
```
$(document).ready(function(){
	$('.OPENMODALWINDOW').on('click', function(event){ 
		event.preventDefault();
// Define spreadsheets URLs.
	var mySpreadsheetTBL1 = 'https://docs.google.com/spreadsheets/d/xx1xx/edit#gid=0';//TABLE 1
	var mySpreadsheetTBL2 = 'https://docs.google.com/spreadsheets/d/xx2xx/edit#gid=0'; //TABLE 2
	var mySpreadsheetTBL3 = 'https://docs.google.com/spreadsheets/d/xx3xx/edit#gid=0'; //TABLE 3
	var mySpreadsheetTBL4 = 'https://docs.google.com/spreadsheets/d/xx4xx/edit#gid=0'; //TABLE 4
	var mySpreadsheetTBL5 = 'https://docs.google.com/spreadsheets/d/xx5xx/edit#gid=0'; //TABLE 5

// Load all spreadsheets
	$('#program01').sheetrock({url: mySpreadsheetTBL1,sql: "select A,B",headersOff: true});
	$('#program02').sheetrock({url: mySpreadsheetTBL2,sql: "select A,B",headersOff: true});
	$('#program03').sheetrock({url: mySpreadsheetTBL3,sql: "select A,B",headersOff: true});
	$('#program04').sheetrock({url: mySpreadsheetTBL4,sql: "select A,B",headersOff: true});
	$('#program05').sheetrock({url: mySpreadsheetTBL5,sql: "select A,B",headersOff: true});

// setTimeout to allow for spreadsheets to be loaded
  	setTimeout(function(){
		$("table:eq(1) tr:eq(1) td:eq(1)").append( "<a href='javascript:void(0);' class='STTable05'>Scroll Down to Table 5</a>" );
		$('.STTable05').on('click',function(){$('.myModal').animate({ scrollTop: $('#program05').offset().top -44 }, 1500);});
	}, 3000);//timeout

});
```
and the html
```
<table id="program01"></table><!-- first Table, 2nd row, 2nd cell append scroll to link -->
<table id="program02"></table>
<table id="program03"></table>
<table id="program04"></table>
<table id="program05"></table>
```
This could be THE solution for what I am after, however, Chris, or anyone else who may have a better/alternate solution...

thanks, Col
