### ISSUE TITLE
Cells and data formats

### ISSUE THREAD

**Issue by kvizzt** [chriszarate/sheetrock#46]
Hi
Thanks a bunch for a easy to use script and a quick setup. 
I have a question if anyone have managed to retrieve a cells data-format type.

For instance in the "G" column in Spreadsheet I use percentage format but it displays as decimal formated numbers when I use sheetrock in HTML. 

Is there a way to keep the google cell formats or a simple way to convert them back to percentage?

I have created a example here where I can't get the column "G" to swow the numbers in %:
http://jsfiddle.net/xhmavwxf/14/ 

The public spreadsheet can be found here:
 https://docs.google.com/spreadsheets/d/1d0wHdIXXHI_rfXY-Fqi0ehIVDuUVxGHfTO8sIZG4UOk/edit

I'm quite new to code so any help would be appreciated. 

— Daniel

**Comment by chriszarate** [comment]
After extensive testing, it doesn't seem like Google's API just doesn't consistently support formatted text in a way that can be relied upon. I've now noted this in the documentation.
