### ISSUE TITLE
Will this work with the Drive API?

### ISSUE THREAD

**Issue by LimeBlast** [chriszarate/sheetrock#53]
I've just received an email from Google telling me that the Documents List API is going to be discontinued:

![email](http://i.imgur.com/iH8GVTn.png)

Is my use of sheetrock going to be affected, or will I need to change something to make it work with the Drive API?? This is my code:

https://github.com/BirminghamIO/freelancers.birmingham.io/blob/gh-pages/js/main.js#L3

Thank you.

**Comment by chriszarate** [comment]
No, this does not affect Sheetrock, which uses the Visualization API. (Short reply while traveling.)

**Comment by LimeBlast** [comment]
Thank you for the reply :+1:
