### ISSUE TITLE
Q. How to get sheet URLs in format for sheetrock

### ISSUE THREAD

**Issue by pr3sidentspence** [chriszarate/sheetrock#55]
I can't seem to get a URL from Google Drive in the format Sheetrock wants. My share links do not have  a gid, which Sheetrock wants. I tried putting the key from my spreadsheet into the space for the key in the examples, but then I get an Access Denied in the console.

Advice?

**Comment by chriszarate** [comment]
Can you provide an example—perhaps a test sheet?

**Comment by pr3sidentspence** [comment]
I did find a way to get a url that works, but here's what I was doing. Using either the share in the upper right, or the publish to web under the File menu Docs would give me this url:

`https://docs.google.com/spreadsheets/d/1Dnpw8UJZ7y4O7pMORp2bj8Atl3DgmY3pTOFtAhHEb4U/edit?usp=sharing`

I did note that the URL in the omnibar of my browser was:

`https://docs.google.com/spreadsheets/d/1Dnpw8UJZ7y4O7pMORp2bj8Atl3DgmY3pTOFtAhHEb4U/edit#gid=0`

which worked.

**Comment by arjanelfassed** [comment]
Hi Chris,

What would be the right url to paste with this one?

https://docs.google.com/spreadsheets/d/1u7K7MWTAlqICyZ07Zw05VFQgmU-cbB97iv-CePI9wnU/pubhtml?gid=1822988381&single=true

I would love to have it working with the DataTables option. Until now we used this one of a colleague http://yerb.net/blog/2014/06/06/using-datatables-with-the-google-fusion-tables-api

But I'd love to use sheetrock for this. Any advice is much appreciated.

Arjan

**Comment by chriszarate** [comment]
Just use the URL in your browser's URL bar when you're looking at the sheet you want to use. That's the format Sheetrock is expecting.
