### ISSUE TITLE
Have sheetrock id or class the table it creates, so that it's easier to manipulate its contents?

### ISSUE THREAD

**Issue by pr3sidentspence** [chriszarate/sheetrock#56]
Is there a way to have sheetrock id or class the table it creates, so that it's easier to manipulate its contents?

**Comment by chriszarate** [comment]
Not sure I understand. Sheetrock doesn't create a table, it uses whatever element you target with it, e.g.,: `$('#myTable').sheetrock(...);`. You can put whatever class you want onto it.

**Comment by peterhuppertz** [comment]
I guess pr3sidentspence is looking for classes/ids for <tr>, <th>, <td>, etc?! You can add these yourself using the "rowHandler" function. Some work, but extremely flexible!

**Comment by chriszarate** [comment]
Closing, feel free to reopen if it's still an issue.
