### ISSUE TITLE
Sheet with 50k rows, datatables - loading slow

### ISSUE THREAD

**Issue by arjanelfassed** [chriszarate/sheetrock#58]
Have a Google Spreadsheet with 50.000 rows. Wanted to use DataTables but it takes a very long time to load, so I entered chunckSize. However, it stops loading then, and doesn't continue in the background. What would be a solution to this?

$('#statistics').sheetrock({
  url: mySpreadsheet,
  chunkSize: 13000,
  userCallback: makeSortable
});

// Make table sortable with jQuery DataTables
// https://datatables.net
// No fancy styling here, just click to sort.
function makeSortable(options) {
  options.target.DataTable();
}

**Comment by chriszarate** [comment]
13,000 is still a pretty high number. I'd suggest a much smaller number, like 200, and then load more if the user scrolls to the bottom of the table. Look into an infinite scroll library for that.
