### ISSUE TITLE
Fix Bootstrap Responsiveness Table

### ISSUE THREAD

**Issue by IrfanFza** [chriszarate/sheetrock#59]
Hi Chris, after I used your great plugin, the bootstrap table responsiveness I used is not working (I have added the table-responsive class). How can I solve this?

**Comment by chriszarate** [comment]
Could you provide some more details? Sheetrock should not interfere in any way with the table's styling—it does not add or remove classes or change surrounding markup.

Here's a fiddle showing a responsive Bootstrap table with Sheetrock:

http://jsfiddle.net/j4dLvpej/

**Comment by chriszarate** [comment]
Closing, feel free to reopen if it's still an issue.
