### ISSUE TITLE
Querying sheets?

### ISSUE THREAD

**Issue by nruth** [chriszarate/sheetrock#60]
I found in the [google docs](https://developers.google.com/chart/interactive/docs/spreadsheets#Google_Spreadsheets_as_a_Data_Source) that gid is for sheet selection, but wonder if there's a way of getting, or interest in having, either:

- all sheets in a tables array, rather than table, passed to dataHandler
- a list of sheet names / indices to query one-by-one

**Comment by chriszarate** [comment]
The API that Sheetrock uses doesn't support iterating over "worksheets"/`gid`s, so this isn't on the radar at the moment. Closing but feel free to reopen with additional questions.
