### ISSUE TITLE
Table Head & Body tags on select option list

### ISSUE THREAD

**Issue by WannesVandamme** [chriszarate/sheetrock#61]
So i've been trying out some stuff with Sheetrock & Handlebars and i noticed that, while the example working with a ordened/unordened list worked fine, if you tried to convert that to a select list the data wouldn't show anymore. eg:
```javascript
<h3>Team RBI</h3>
<select id="team-rbi">
  <script id="team-rbi-template" type="text/x-handlebars-template">
    <option value="{{cells.TeamRBI}}"><strong>{{cells.TeamName}}</strong></option>
  </script>
</select>
```
would show an empty select list.
now after a lot of searching i found that the output looked like this:
```javascript
<body>
  <h3>Team RBI</h3>

<select id="team-rbi">
  <script id="team-rbi-template" type="text/x-handlebars-template">
    <option value="{{cells.TeamRBI}}"><strong>{{cells.TeamName}}</strong></option>
  </script>
<thead></thead><tbody>
    <option value="686">NYM</option>
  
    <option value="638">PHI</option>
  
    <option value="614">CIN</option>
  
    <option value="595">SFG</option>
  
    <option value="591">SDP</option>
  </tbody></select>
</body>
```
Is there a way to prevent the `<thead>` and `<tbody>` tags?

Thanx!

**Comment by chriszarate** [comment]
Yes, pass `rowGroups: false` in the options. This will be handled better in future versions.

**Comment by WannesVandamme** [comment]
That works indeed. Thank you for a quick response.
