### ISSUE TITLE
Prevent Header Rows From Being Returned in Results

### ISSUE THREAD

**Issue by joshglenn** [chriszarate/sheetrock#62]
Sheetrock is working great. But I don't know how to keep the header rows from my spreadsheet from being returned in the result set. What is the best way to prevent that?

**Comment by chriszarate** [comment]
The documentation on the main repo page describes the `headersOff` option. Setting it to `true` should do the trick. You sometimes need to combine it with the `headers` option.

**Comment by joshglenn** [comment]
I have tried the headersoff option. So I must be doing something wrong. Here's my code:

```
$('#mydiv').sheetrock({
  url: mySpreadsheet,
  sql: "select A,B",
  headersOff: true,
  headers: 1,
  labels: ['Word', 'Meaning'],
  rowHandler: WordsTemplate
});
```

You see any reason why I'm having trouble?

**Comment by joshglenn** [comment]
Okay, I got it to do what I want. However, I had to tell it that I have 2 header rows in order for the 1 header row that I have not to appear in the result set.

Thanks for this tool by the way. I think its quite good.

**Comment by chriszarate** [comment]
Cool, glad you got it to work. Google Spreadsheets can be really unpredictable about what it considers the header row. For future reference, it sometimes helps to play with "freezing" rows (View > Freeze rows). I haven't quite sorted out a pattern.
