### ISSUE TITLE
Dynamically Change URL

### ISSUE THREAD

**Issue by killroyboy** [chriszarate/sheetrock#63]
I would like to dynamically change the URL based on user selection. I don't see a way to "refresh" the URL or even destroy the widget in order to re-initialize.

Is there a way to do what I am trying?

**Comment by chriszarate** [comment]
The URL is passed in the options. There is no need to destroy or re-initialize the widget; Sheetrock can handle multiple requests on the same page simultaneously. (The [homepage][1] does this.)

What Sheetrock does expect is a 1:1 relationship between a request and a DOM element. If you want to use a different URL (and thus initiate a different request), use a different DOM element. Doing this programmatically in response to a user's selection means you'll need to create the elements on the fly. With jQuery, this is pretty easy to implement and could go something like:

```js
$('<table/>').appendTo('#container').sheetrock({url: '...' /* options */});
```

If you want to remove the table later, assign it to a variable and `.remove()` it, or just empty out the container.

[1]: http://chriszarate.github.io/sheetrock/

**Comment by killroyboy** [comment]
I was taking a different approach, but this works. I was wanting to just use a single DOM element and just change the data within it. This way is just a little more code on my end, but it's functional. Thanks Chris.
