### ISSUE TITLE
Lazy-load question

### ISSUE THREAD

**Issue by mrsq** [chriszarate/sheetrock#64]
Hello,
First of all, this plug-in is great, thank you for taking the time to build and maintain it.
I have a question on implementing lazy-load, and was hoping you could help. 
I have my content loading in on page load and a chunkSize of 8, I have my scroll set up to call a function, but I don't know how to keep pulling more data. I am not sure how to call sheetrock to load more data. 
Any help would be greatly appreciated :)
Thank you.
This is my code:
```
function loadData() {
        var query = $.extend({});
              query.sql = "select B,C,D,E,F,G, H, I, J order by A desc";
              query.rowHandler = HRTemplate;
		query.rowGroups = false;
		query.headersOff = true;
		query.url = mySpreadsheet;
		query.chunkSize = 8;
                 query.userCallback = init;
        $spreadsheet.sheetrock(query);
}
```
For example: right arrow on infinite scroll:
```
                $('.right-arrow').on('click', function() {
                    if (myScroll.x >= -entireWidth) {
                        myScroll.scrollBy(-500, 0, 280);
                     loadContent();
}
  }
```

**Comment by chriszarate** [comment]
I don't see anything wrong with your code other than the fact that your function is named `loadData` but you are calling `loadContent`. Perhaps that's a typo, though. 

If you could set up a jsFiddle I could help troubleshoot further.

**Comment by mrsq** [comment]
Thank you for the reply. You are right it is working. The added rows were just being hidden by another plugin (facepalm). Sorry for bothering you and keep up the great work!

**Comment by chriszarate** [comment]
No problem! Glad you figured it out.
