### ISSUE TITLE
Google Chrome Issuu

### ISSUE THREAD

**Issue by sleepymonday** [chriszarate/sheetrock#67]
Hi.
Thank you for this very useful script. 
I'm having issues showing the data on Chrome. Safari works fine, but Chrome and Firefox doesn't show any data at all. Can you please help me to understand what am I doing wrong?

This is the webpage where I'm using the script:
http://gabrielboric.cl/laidea/

Thank you very much !

**Comment by chriszarate** [comment]
Looks like a permissions issue. The Sheet should be public. Most likely you are signed into your Google account in Safari (and therefore have access) but are not signed in in Chrome and Firefox.

https://support.google.com/drive/bin/answer.py?hl=en&answer=2494822

**Comment by sleepymonday** [comment]
Chris: Thank you so much. I feel so sorry I bothered you. Sometimes the simplest solution is right in front of us and we just can't see it. Thanks again.

**Comment by chriszarate** [comment]
No problem at all! Take care.
