### ISSUE TITLE
Pass params to callback function

### ISSUE THREAD

**Issue by VMRuiz** [chriszarate/sheetrock#69]
Hi, I'd like to pass additional info to the callback function, Do you know an easy way to do it?

Great work, by the way!

**Comment by chriszarate** [comment]
Currently, unsupported options are stripped out before being passed to the callback function, so you can't pass it that way. I'll consider adding a custom data option that facilitates this. Until then:

If the additional info is static, put it in a variable in the same scope:

```js
var myData = {/* additional info */};

var myCallback = function (error, options, response) {
  console.log(myData);
};

sheetrock({
  /* options */
  callback: myCallback
});
```

If it's specific to the request and you are making multiple requests, bake it into the callback function:

```js
var myCallback = function (error, options, response, myData) {
   console.log(myData);
};

sheetrock({
  /* options */
  callback: function (error, options, response) {
    var dataForThisRequest = {/* additional info */};
    myCallback(error, options, response, dataForThisRequest);
  }
});
```

**Comment by VMRuiz** [comment]
Hi, I already found a way, and I think that is easier:

1) Add an extra param, call it params for example

```javascript
  var defaults = {
    url:          '',          // String  -- Google Sheet URL
    query:        '',          // String  -- Google Visualization API query
    target:       null,        // DOM Element -- An element to append output to
    fetchSize:    0,           // Integer -- Number of rows to fetch (0 = all)
    labels:       [],          // Array   -- Override *returned* column labels
    rowTemplate:  null,        // Function / Template
    callback:     null,        // Function
    params:       {}, 
    reset:        false        // Boolean -- Reset request status
  };

```

2) Call sheetrock adding the new param

```javascript
  sheetrock({ url:spreadsheets.url, callback: myCallback, params:{"color":spreadsheets.color}});
```

3) Retrieve data in callback function from options object:
```javascript
   options.user.params.color
```

**Comment by chriszarate** [comment]
Nice, that will work. You're effectively implementing your own params option. In fact, you could accomplish the same thing without modifying Sheetrock's source code:

```js
sheetrock.defaults.params = {};
```

**Comment by VMRuiz** [comment]
Wow, I didn't know this one, I have a lot to learn yet.
Your library made my job easier, thanks for your contribution to the community.

**Comment by benjaroa** [comment]
This should be in the documentation at the home screen, very useful!

I was working with a `for` to process a lot of sheets and the scope didn't allow me to call `i` (auxiliar variable) to operate the array (no idea why).

``` javascript
// [name,google_key,gid_1,gid_2]
var urls = [
	["one","asdlkmalskmfergoogle_key","0","356600466"],
	["two","1D-asdlkmalskmfergoogle_key","0","1651706596"]
]; 
for(i=0;i<urls.length;i++){
	sheetrock({
		url: "https://docs.google.com/spreadsheets/d/"+url[j][1]+"#gid="+url[j][2]
		callback: function (error, options, response) {
			console.log(i); // always 2!
...
```

Using `params:{"i":i},` was the solution!

Thanks
