### ISSUE TITLE
DataTables integration examples no longer working

### ISSUE THREAD

**Issue by DanSias** [chriszarate/sheetrock#70]
I'm having trouble getting Sheetrock integrated with [DataTables](https://www.datatables.net/).

There are a couple closed issues with jsFiddles that, unfortunately, no longer run.

* [#51](https://github.com/chriszarate/sheetrock/issues/51) links to this [Fiddle](http://jsfiddle.net/m04ddeu2/162/) that produces no result.

* [#11](https://github.com/chriszarate/sheetrock/issues/11) is about a similar table sorting plugin, with a [Fiddle](http://jsfiddle.net/6Eg7y/) that also has no result.

There's a "Page not found" error on the [jquery.sheetrock.min.js](http://chriszarate.github.io/sheetrock/dist/jquery.sheetrock.min.js) in the external resources, updating that to sheetrock.min.js renders a table, but not a sortable, searchable DataTable. Also, the first row is a result, not column headers.

Sheetrock makes querying a massive spreadsheet fast and easy, and if I could integrate with DataTables that would be ideal. I'd love to see a working example.

Thanks for all the work you put into this, it's a great project.

**Comment by chriszarate** [comment]
The API changed with v1.0.0, so some of the old fiddles no longer work.

Here's an updated one:

http://jsfiddle.net/chriszarate/m04ddeu2/495/

**Comment by DanSias** [comment]
Perfect, thank you. Does just what I needed.
