### ISSUE TITLE
Change format to 2 decimal places

### ISSUE THREAD

**Issue by markjcasey** [chriszarate/sheetrock#74]
Hi

I'm grabbing some data from cells in Google Sheets that display as 7.26, 7.11 etc

Sheetrock is displaying them in the HTML as 7.257421964000912, 7.107236842105261 etc

Is it possible to display them the same as they are in Google sheets?

I tried looking into the format clause of Google Visualization API Query Language https://developers.google.com/chart/interactive/docs/querylanguage#format

I couldn't get that working though.

Any ideas?

Thanks

**Comment by chriszarate** [comment]
Most formatting info (which includes number formatting) doesn't get reliably passed through via the API, so Sheetrock can't represent it. You'll have to do the rounding in your template or callback function.

**Comment by nickautomatic** [comment]
I've made a tweak (see above pull request) to use formatted values, which seems to achieve the required effect. (nb. I'm not currently able to run the test suite, so can't promise I haven't broken anything, but it's working for my purposes!)

**Comment by chriszarate** [comment]
Thanks! I'll take a look and update the test suite.
