### ISSUE TITLE
Zero values dissapear

### ISSUE THREAD

**Issue by kinder2003** [chriszarate/sheetrock#78]
Hi. Some of numeric values I am trying to extract from my spreadsheet are equal to zero ("0"). In HTML, however, all I can see are empty cells (empty values).
I checked, the same thing happens in your example with 5 baseball players (https://jsfiddle.net/chriszarate/09sknz54/light/) if you fetch all the players. The lowest players will have no HR value.

**Comment by chriszarate** [comment]
This looks to be an issue with Google's API. Will investigate.

**Comment by chriszarate** [comment]
This issue was fixed with #81 and `v1.0.1`.
