### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by diskmaster23** [chriszarate/sheetrock#79]
I was wondering if there was a caching option for Sheetrock.js? I know with DataTables that is it available, but I don't know if it is available via your script. 
Please advise. 

Thanks advance.

**Comment by chriszarate** [comment]
There isn't a built-in caching mechanism, but you can flexibly do whatever you want via the `callback` option, to which the data is passed.

```js
sheetrock({
  /* options */
  callback: function (error, options, response) {
    /* do something with response */
  }
});
```
