### ISSUE TITLE
How to populate conditional selection fields

### ISSUE THREAD

**Issue by dtwsolutions** [chriszarate/sheetrock#83]
I have a dropdown selection field that I have successfully populated with data from a Google sheet using sheetrock, but that is only part of what I need. I need to populate a 2nd dropdown field with data from the same sheet, but with a query based on the selection made in the previous field. Any suggestions??

**Comment by chriszarate** [comment]
This is outside the scope of Sheetrock, but you should investigate how to use jQuery's `on` function to listen to the `change` event of the first drop down. Then get the [value of the selected option](https://learn.jquery.com/using-jquery-core/faq/how-do-i-get-the-text-value-of-a-selected-option/), make another request, and populate the second drop-down.

**Comment by dtwsolutions** [comment]
Yes I ended up using javascript and ajax to get the job done, but couldn't use sheetrock. I had to access the Google sheet getting the data in a CSV format that I converted into a PHP array. Then built my fields from there. Thanks anyway!
