### ISSUE TITLE
when pasting values (even when typing sometimes) the value will not print

### ISSUE THREAD

**Issue by szyam** [chriszarate/sheetrock#84]
I've noticed this a few times, and can't seem to find exactly whats causing it.

I begin my new sheets by duplicating a previous one, then clearing the values. Or, this time i just copied the header and pasted it into a new file.

When I begin to add values, in this case "names", I refresh the site pulling it in and they do not appear. It does however create the correct amount of <li> items, but there empty?

Here's a link to where im using it as an example. It is working as expected here though.
http://electricagenda.com/2016/holyship

btw, awesome script! working great for my app (besides above)

**Comment by chriszarate** [comment]
I'm not sure I understand the issue. Could you provide an example/fiddle that demonstrates the problem?

**Comment by chriszarate** [comment]
Closing, please feel free to reopen if the issue persists.

**Comment by szyam** [comment]
Yes I wasn't able to make a fiddle of issue but will try a different route if I encounter this again. Thank you!
