### ISSUE TITLE
Header row is included in results

### ISSUE THREAD

**Issue by fatuhoku** [chriszarate/sheetrock#85]
README says:
> - One header row. Sheetrock expects a single header row of column labels in the first row of the Sheet. Any other configuration (e.g., no header row, multiple or offset header rows) can cause problems with the request and complicates templating.

But when I run example:

```
sheetrock({
  url: "https://docs.google.com/spreadsheets/d/1qT1LyvoAcb0HTsi2rHBltBVpUBumAUzT__rhMvrz5Rk/edit#gid=0",
  query: "select A,B,C,D,E,L where E = 'Both' order by L desc",
  callback: myCallback
});
```

You get:

```
[ { cells: 
     { Team: 'Team',
       Pos: 'Pos',
       First: 'First',
       Last: 'Last',
       Bats: 'Bats',
       BA: 'BA' },
    cellsArray: [ 'Team', 'Pos', 'First', 'Last', 'Bats', 'BA' ],
    labels: [ 'Team', 'Pos', 'First', 'Last', 'Bats', 'BA' ],
    num: 0 },
...
```

**Comment by chriszarate** [comment]
I may be misunderstanding something, because this is the expected behavior to me. The header itself is returned as one of the rows. The `num` value is `0` which indicates a header row.

**Comment by fatuhoku** [comment]
@chriszarate Ah. Well the README made it sound like I HAVE to have a header row, otherwise things just won't work. When in fact, this is untrue. sheetrock works just as well without a header row as with a header row.

**Comment by chriszarate** [comment]
It is mentioned in the `rowTemplate` documentation, but I'll add another more obvious note.

**Comment by fatuhoku** [comment]
Thanks that's clearer for sure.
