### ISSUE TITLE
Select by header

### ISSUE THREAD

**Issue by fatuhoku** [chriszarate/sheetrock#86]
It'll be great to write something like

`select name` rather than `select A`, which seems really hardcoded.

**Comment by chriszarate** [comment]
Good idea! In fact, I implemented this in `0.2.x`, but it required an initial AJAX request to retrieve the headers, then another to submit the actual query. The performance penalty was a bummer. It also had edge case problems like user typos and duplicate header values (if you have two columns named "name," which do we use?).

**Comment by fatuhoku** [comment]
Ah. @chriszarate I can understand the challenges. Have you had any further ideas on how to overcome these issues?

**Comment by chriszarate** [comment]
I'm unlikely to restore this functionality for the reasons outlined above, but it would be fairly simple to write your own implementation with known column labels. Using ES5:

```js
var myLabels = {
  'A': 'name',
  'B': 'address',
  'C': 'zip'
};

var myQuery = "select %name%,%address% where %zip% = '12345' order by %name% asc";

Object.keys(myLabels).forEach(function (column) {
  var pattern = new RegExp('%' + myLabels[column] + '%', 'g');
  myQuery = myQuery.replace(pattern, column);
});
```

I recommend wrapping your column names in a symbol like "%" as above to avoid collisions with SQL instructions.

If you wanted to retrieve the column names dynamically, then you could easily put the above in a Sheetrock callback, getting the labels from the response object. Then send your actual request.

**Comment by fatuhoku** [comment]
Yep that's sort of what I ended up doing — having some sort of 'schema' object. It's not ideal but makes the code much more self-descriptive. thanks.
