### ISSUE TITLE
'Pin' accepted certificates to Google Sheets

### ISSUE THREAD

**Issue by fatuhoku** [chriszarate/sheetrock#87]
Thanks for this project — it's so cool that it's possible to host static data on Google Spreadsheets.

Using HTTPS to connect to Sheets ensures the data transferred is encrypted, but does not ensure that you're really talking to Google Sheets. A man-in-the-middle can easily present a valid certificate for a different domain and sheetrock will happily serve that data up.

The certificate of Google Sheets must be pinned.  I think you can do this through `request`... see https://github.com/request/request#using-optionsagentoptions.

**Comment by chriszarate** [comment]
Good idea ... I'll take a look.

**Comment by chriszarate** [comment]
It looks to me like cert pinning is not directly supported by `request`, but could be implemented with an alternative module like [`request-ssl`](https://github.com/jhaynie/request-ssl). 

I'm a little worried about implementing this in a library, where a hardcoded fingerprint could become outdated and break applications—i.e., in a dependency chain one doesn't control. This seems better suited to implement at the application level.

In Sheetrock `1.0.1`, it's now possible to side-shim your own `request` module as long as it provides the same API. So you could do something like:

```js
var sheetrock = require('sheetrock');
var request = require('require-ssl'); 

// Add fingerprint for Google API endpoint.
request.addFingerprint('docs.google.com', '[fingerprint]');

// Side-shim request-ssl.
sheetrock.environment.request = request;

sheetrock({
  url: "https://docs.google.com/[...]",
  callback: function (error, options, response) {
    // If fingerprint is not verified, error object will contain more information.
  }
});
```

To be clear, this is only applicable to using Sheetrock in Node.js. In the browser, certificate pinning is already implemented in recent versions of Firefox and Chrome.
