### ISSUE TITLE
"Synchronous XMLHttpRequest on the main thread is deprecated"

### ISSUE THREAD

**Issue by zecanovaes** [chriszarate/sheetrock#89]
First of all, thank you for this project. You saved my life, really.

My question is about the alert in Chrome and Firefox, pointing this use of **Synchronous XMLHttpRequest** when I get my spreadsheet data with Sheetrock. 

Any ideia about what's wrong? Thanks!

**Comment by chriszarate** [comment]
In the browser, Sheetrock doesn't use `XMLHttpRequest` at all—instead it adds script tags to the DOM to fetch JSONP. Further, I don't see this error on Sheetrock's homepage, which loads data multiple times.

Could you provide a jsfiddle that replicates this error?

**Comment by chriszarate** [comment]
Feel free to reopen if you can replicate.
