### ISSUE TITLE
If no row found, how to show custom error message?

### ISSUE THREAD

**Issue by ohid** [chriszarate/sheetrock#94]
I am wondering  if no row found after fetching query data it is still showing the table headers. But I want to manipulate the DOM and give a message that, "Sorry no results found for that roll".

Here is the example on jsfiddle. If I try to get a roll 250 then no row found. Then I want to give a message to the user that no results found.

https://jsfiddle.net/7krs6q0q/334/

Any help would be highly appreciated. 
Thanks

**Comment by tjferry14** [comment]
Update your function: 
```
// Load top ten switch hitters.
$('#switch-hitters').sheetrock({
  url: mySpreadsheet,
  query: "select A,B,C,D,E,L where A = 143", // this will select no results
  fetchSize: 10,
  callback: function (error, options, response){
      if(!error){
        if ($('#switch-hitters tr').length == 1) {
          $('#switch-hitters').append("<h3>No results.</h3>")
        }
      } else {
        $('#switch-hitters').append('<h3>Error.</h3>');
      }
    }
});


```
